services:
  server:
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
      target: server # 🎯 Triggers the self-contained server stage
    container_name: chat_server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    env_file:
      - .env
    depends_on:
      migration-runner:
        condition: service_completed_successfully

  migration-runner:
    image: migration-runner
    build:
      context: .
      dockerfile: Server/Dockerfile
      target: migration # 🎯 Triggers the self-contained migration stage
    container_name: chat_migration_runner
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    shm_size: 256mb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: client
    container_name: chat_client
    ports:
      - "5173:80"
#    depends_on:
#      server:
#        condition: service_healthy

volumes:
  pgdata:

