// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addMembers, createDirectMessage, createRoom, getConfirmEmail, getManageInfo, getMessages, listRooms, listUsers, type Options, postForgotPassword, postLogin, postLogout, postManage2Fa, postManageInfo, postRefresh, postRegister, postResendConfirmationEmail, postResetPassword, sendMessages } from '../sdk.gen';
import type { AddMembersData, AddMembersError, AddMembersResponse, CreateDirectMessageData, CreateDirectMessageResponse, CreateRoomData, CreateRoomResponse2, GetConfirmEmailData, GetManageInfoData, GetManageInfoError, GetManageInfoResponse, GetMessagesData, GetMessagesResponse2, ListRoomsData, ListRoomsResponse, ListUsersData, ListUsersResponse2, PostForgotPasswordData, PostForgotPasswordError, PostLoginData, PostLoginResponse, PostLogoutData, PostManage2FaData, PostManage2FaError, PostManage2FaResponse, PostManageInfoData, PostManageInfoError, PostManageInfoResponse, PostRefreshData, PostRefreshResponse, PostRegisterData, PostRegisterError, PostResendConfirmationEmailData, PostResetPasswordData, PostResetPasswordError, SendMessagesData, SendMessagesResponse } from '../types.gen';

export const postRegisterMutation = (options?: Partial<Options<PostRegisterData>>): UseMutationOptions<unknown, PostRegisterError, Options<PostRegisterData>> => {
    const mutationOptions: UseMutationOptions<unknown, PostRegisterError, Options<PostRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postLoginMutation = (options?: Partial<Options<PostLoginData>>): UseMutationOptions<PostLoginResponse, DefaultError, Options<PostLoginData>> => {
    const mutationOptions: UseMutationOptions<PostLoginResponse, DefaultError, Options<PostLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postRefreshMutation = (options?: Partial<Options<PostRefreshData>>): UseMutationOptions<PostRefreshResponse, DefaultError, Options<PostRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostRefreshResponse, DefaultError, Options<PostRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getConfirmEmailQueryKey = (options: Options<GetConfirmEmailData>) => createQueryKey('getConfirmEmail', options);

export const getConfirmEmailOptions = (options: Options<GetConfirmEmailData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getConfirmEmailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConfirmEmail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConfirmEmailQueryKey(options)
});

export const postResendConfirmationEmailMutation = (options?: Partial<Options<PostResendConfirmationEmailData>>): UseMutationOptions<unknown, DefaultError, Options<PostResendConfirmationEmailData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostResendConfirmationEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postResendConfirmationEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postForgotPasswordMutation = (options?: Partial<Options<PostForgotPasswordData>>): UseMutationOptions<unknown, PostForgotPasswordError, Options<PostForgotPasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, PostForgotPasswordError, Options<PostForgotPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postForgotPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postResetPasswordMutation = (options?: Partial<Options<PostResetPasswordData>>): UseMutationOptions<unknown, PostResetPasswordError, Options<PostResetPasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, PostResetPasswordError, Options<PostResetPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postResetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postManage2FaMutation = (options?: Partial<Options<PostManage2FaData>>): UseMutationOptions<PostManage2FaResponse, PostManage2FaError, Options<PostManage2FaData>> => {
    const mutationOptions: UseMutationOptions<PostManage2FaResponse, PostManage2FaError, Options<PostManage2FaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postManage2Fa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getManageInfoQueryKey = (options?: Options<GetManageInfoData>) => createQueryKey('getManageInfo', options);

export const getManageInfoOptions = (options?: Options<GetManageInfoData>) => queryOptions<GetManageInfoResponse, GetManageInfoError, GetManageInfoResponse, ReturnType<typeof getManageInfoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getManageInfo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getManageInfoQueryKey(options)
});

export const postManageInfoMutation = (options?: Partial<Options<PostManageInfoData>>): UseMutationOptions<PostManageInfoResponse, PostManageInfoError, Options<PostManageInfoData>> => {
    const mutationOptions: UseMutationOptions<PostManageInfoResponse, PostManageInfoError, Options<PostManageInfoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postManageInfo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postLogoutMutation = (options?: Partial<Options<PostLogoutData>>): UseMutationOptions<unknown, DefaultError, Options<PostLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addMembersMutation = (options?: Partial<Options<AddMembersData>>): UseMutationOptions<AddMembersResponse, AddMembersError, Options<AddMembersData>> => {
    const mutationOptions: UseMutationOptions<AddMembersResponse, AddMembersError, Options<AddMembersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addMembers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createDirectMessageMutation = (options?: Partial<Options<CreateDirectMessageData>>): UseMutationOptions<CreateDirectMessageResponse, DefaultError, Options<CreateDirectMessageData>> => {
    const mutationOptions: UseMutationOptions<CreateDirectMessageResponse, DefaultError, Options<CreateDirectMessageData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createDirectMessage({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRoomsQueryKey = (options?: Options<ListRoomsData>) => createQueryKey('listRooms', options);

export const listRoomsOptions = (options?: Options<ListRoomsData>) => queryOptions<ListRoomsResponse, DefaultError, ListRoomsResponse, ReturnType<typeof listRoomsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRooms({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRoomsQueryKey(options)
});

export const createRoomMutation = (options?: Partial<Options<CreateRoomData>>): UseMutationOptions<CreateRoomResponse2, DefaultError, Options<CreateRoomData>> => {
    const mutationOptions: UseMutationOptions<CreateRoomResponse2, DefaultError, Options<CreateRoomData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRoom({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMessagesQueryKey = (options: Options<GetMessagesData>) => createQueryKey('getMessages', options);

export const getMessagesOptions = (options: Options<GetMessagesData>) => queryOptions<GetMessagesResponse2, DefaultError, GetMessagesResponse2, ReturnType<typeof getMessagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMessagesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getMessagesInfiniteQueryKey = (options: Options<GetMessagesData>): QueryKey<Options<GetMessagesData>> => createQueryKey('getMessages', options, true);

export const getMessagesInfiniteOptions = (options: Options<GetMessagesData>) => {
    const opts = infiniteQueryOptions<GetMessagesResponse2, DefaultError, InfiniteData<GetMessagesResponse2>, QueryKey<Options<GetMessagesData>>, string | null | Pick<QueryKey<Options<GetMessagesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetMessagesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    cursor: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getMessages({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getMessagesInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const sendMessagesMutation = (options?: Partial<Options<SendMessagesData>>): UseMutationOptions<SendMessagesResponse, DefaultError, Options<SendMessagesData>> => {
    const mutationOptions: UseMutationOptions<SendMessagesResponse, DefaultError, Options<SendMessagesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendMessages({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse2, DefaultError, ListUsersResponse2, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});
