// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddMembersData, AddMembersErrors, AddMembersResponses, CreateDirectMessageData, CreateDirectMessageErrors, CreateDirectMessageResponses, CreateRoomData, CreateRoomErrors, CreateRoomResponses, GetConfirmEmailData, GetConfirmEmailResponses, GetManageInfoData, GetManageInfoErrors, GetManageInfoResponses, GetMessagesData, GetMessagesErrors, GetMessagesResponses, ListRoomsData, ListRoomsErrors, ListRoomsResponses, ListUsersData, ListUsersErrors, ListUsersResponses, PostForgotPasswordData, PostForgotPasswordErrors, PostForgotPasswordResponses, PostLoginData, PostLoginResponses, PostLogoutData, PostLogoutResponses, PostManage2FaData, PostManage2FaErrors, PostManage2FaResponses, PostManageInfoData, PostManageInfoErrors, PostManageInfoResponses, PostRefreshData, PostRefreshResponses, PostRegisterData, PostRegisterErrors, PostRegisterResponses, PostResendConfirmationEmailData, PostResendConfirmationEmailResponses, PostResetPasswordData, PostResetPasswordErrors, PostResetPasswordResponses, SendMessagesData, SendMessagesErrors, SendMessagesResponses } from './types.gen';
import { zAddMembersBody, zAddMembersPath, zAddMembersResponse, zCreateDirectMessageBody, zCreateDirectMessageResponse, zCreateRoomBody, zCreateRoomResponse2, zGetConfirmEmailQuery, zGetManageInfoResponse, zGetMessagesPath, zGetMessagesQuery, zGetMessagesResponse2, zListRoomsResponse, zListUsersResponse2, zPostForgotPasswordBody, zPostLoginBody, zPostLoginQuery, zPostLoginResponse, zPostLogoutBody, zPostManage2FaBody, zPostManage2FaResponse, zPostManageInfoBody, zPostManageInfoResponse, zPostRefreshBody, zPostRefreshResponse, zPostRegisterBody, zPostResendConfirmationEmailBody, zPostResetPasswordBody, zSendMessagesBody, zSendMessagesPath, zSendMessagesResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const postRegister = <ThrowOnError extends boolean = false>(options: Options<PostRegisterData, ThrowOnError>): RequestResult<PostRegisterResponses, PostRegisterErrors, ThrowOnError> => (options.client ?? client).post<PostRegisterResponses, PostRegisterErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostRegisterBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postLogin = <ThrowOnError extends boolean = false>(options: Options<PostLoginData, ThrowOnError>): RequestResult<PostLoginResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostLoginResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostLoginBody,
        path: z.never().optional(),
        query: zPostLoginQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zPostLoginResponse.parseAsync(data),
    url: '/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postRefresh = <ThrowOnError extends boolean = false>(options: Options<PostRefreshData, ThrowOnError>): RequestResult<PostRefreshResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostRefreshResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostRefreshBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zPostRefreshResponse.parseAsync(data),
    url: '/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getConfirmEmail = <ThrowOnError extends boolean = false>(options: Options<GetConfirmEmailData, ThrowOnError>): RequestResult<GetConfirmEmailResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetConfirmEmailResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zGetConfirmEmailQuery
    }).parseAsync(data),
    url: '/confirmEmail',
    ...options
});

export const postResendConfirmationEmail = <ThrowOnError extends boolean = false>(options: Options<PostResendConfirmationEmailData, ThrowOnError>): RequestResult<PostResendConfirmationEmailResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostResendConfirmationEmailResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostResendConfirmationEmailBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/resendConfirmationEmail',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postForgotPassword = <ThrowOnError extends boolean = false>(options: Options<PostForgotPasswordData, ThrowOnError>): RequestResult<PostForgotPasswordResponses, PostForgotPasswordErrors, ThrowOnError> => (options.client ?? client).post<PostForgotPasswordResponses, PostForgotPasswordErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostForgotPasswordBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/forgotPassword',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postResetPassword = <ThrowOnError extends boolean = false>(options: Options<PostResetPasswordData, ThrowOnError>): RequestResult<PostResetPasswordResponses, PostResetPasswordErrors, ThrowOnError> => (options.client ?? client).post<PostResetPasswordResponses, PostResetPasswordErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostResetPasswordBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/resetPassword',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postManage2Fa = <ThrowOnError extends boolean = false>(options: Options<PostManage2FaData, ThrowOnError>): RequestResult<PostManage2FaResponses, PostManage2FaErrors, ThrowOnError> => (options.client ?? client).post<PostManage2FaResponses, PostManage2FaErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostManage2FaBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zPostManage2FaResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/manage/2fa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getManageInfo = <ThrowOnError extends boolean = false>(options?: Options<GetManageInfoData, ThrowOnError>): RequestResult<GetManageInfoResponses, GetManageInfoErrors, ThrowOnError> => (options?.client ?? client).get<GetManageInfoResponses, GetManageInfoErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetManageInfoResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/manage/info',
    ...options
});

export const postManageInfo = <ThrowOnError extends boolean = false>(options: Options<PostManageInfoData, ThrowOnError>): RequestResult<PostManageInfoResponses, PostManageInfoErrors, ThrowOnError> => (options.client ?? client).post<PostManageInfoResponses, PostManageInfoErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostManageInfoBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zPostManageInfoResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/manage/info',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postLogout = <ThrowOnError extends boolean = false>(options: Options<PostLogoutData, ThrowOnError>): RequestResult<PostLogoutResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostLogoutResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostLogoutBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const addMembers = <ThrowOnError extends boolean = false>(options: Options<AddMembersData, ThrowOnError>): RequestResult<AddMembersResponses, AddMembersErrors, ThrowOnError> => (options.client ?? client).post<AddMembersResponses, AddMembersErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zAddMembersBody,
        path: zAddMembersPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zAddMembersResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms/{roomId}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const createDirectMessage = <ThrowOnError extends boolean = false>(options: Options<CreateDirectMessageData, ThrowOnError>): RequestResult<CreateDirectMessageResponses, CreateDirectMessageErrors, ThrowOnError> => (options.client ?? client).post<CreateDirectMessageResponses, CreateDirectMessageErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateDirectMessageBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateDirectMessageResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms/dm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listRooms = <ThrowOnError extends boolean = false>(options?: Options<ListRoomsData, ThrowOnError>): RequestResult<ListRoomsResponses, ListRoomsErrors, ThrowOnError> => (options?.client ?? client).get<ListRoomsResponses, ListRoomsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListRoomsResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms',
    ...options
});

export const createRoom = <ThrowOnError extends boolean = false>(options: Options<CreateRoomData, ThrowOnError>): RequestResult<CreateRoomResponses, CreateRoomErrors, ThrowOnError> => (options.client ?? client).post<CreateRoomResponses, CreateRoomErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateRoomBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateRoomResponse2.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getMessages = <ThrowOnError extends boolean = false>(options: Options<GetMessagesData, ThrowOnError>): RequestResult<GetMessagesResponses, GetMessagesErrors, ThrowOnError> => (options.client ?? client).get<GetMessagesResponses, GetMessagesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zGetMessagesPath,
        query: zGetMessagesQuery
    }).parseAsync(data),
    responseValidator: async (data) => await zGetMessagesResponse2.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms/{roomId}/messages',
    ...options
});

export const sendMessages = <ThrowOnError extends boolean = false>(options: Options<SendMessagesData, ThrowOnError>): RequestResult<SendMessagesResponses, SendMessagesErrors, ThrowOnError> => (options.client ?? client).post<SendMessagesResponses, SendMessagesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zSendMessagesBody,
        path: zSendMessagesPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zSendMessagesResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms/{roomId}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListUsersResponse2.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options
});
