// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type HttpValidationProblemDetails = ProblemDetails & {
    errors?: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type AccessTokenResponse = {
    tokenType?: string;
    accessToken: string;
    expiresIn: number;
    refreshToken: string;
};

export type LoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: string | null;
    twoFactorRecoveryCode?: string | null;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type ResendConfirmationEmailRequest = {
    email: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    email: string;
    resetCode: string;
    newPassword: string;
};

export type TwoFactorResponse = {
    sharedKey: string;
    recoveryCodesLeft: number;
    recoveryCodes?: Array<string> | null;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type TwoFactorRequest = {
    enable?: boolean | null;
    twoFactorCode?: string | null;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type InfoResponse = {
    email: string;
    isEmailConfirmed: boolean;
};

export type InfoRequest = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

export type SignInManagerOfIdentityUser = {
    logger?: ILogger;
    userManager?: UserManagerOfIdentityUser;
    claimsFactory?: IuserClaimsPrincipalFactoryOfIdentityUser;
    options?: IdentityOptions;
    authenticationScheme?: string;
    context?: HttpContext;
};

export type ILogger = {
    [key: string]: never;
};

export type UserManagerOfIdentityUser = {
    logger?: ILogger;
    passwordHasher?: IPasswordHasherOfIdentityUser;
    userValidators?: Array<IuserValidatorOfIdentityUser>;
    passwordValidators?: Array<IPasswordValidatorOfIdentityUser>;
    keyNormalizer?: ILookupNormalizer;
    errorDescriber?: IdentityErrorDescriber;
    options?: IdentityOptions;
    serviceProvider?: IServiceProvider;
    supportsUserAuthenticationTokens?: boolean;
    supportsUserAuthenticatorKey?: boolean;
    supportsUserTwoFactorRecoveryCodes?: boolean;
    supportsUserTwoFactor?: boolean;
    supportsUserPassword?: boolean;
    supportsUserSecurityStamp?: boolean;
    supportsUserRole?: boolean;
    supportsUserLogin?: boolean;
    supportsUserEmail?: boolean;
    supportsUserPhoneNumber?: boolean;
    supportsUserClaim?: boolean;
    supportsUserLockout?: boolean;
    supportsQueryableUsers?: boolean;
    supportsUserPasskey?: boolean;
    users?: Array<IdentityUser>;
};

export type IPasswordHasherOfIdentityUser = {
    [key: string]: never;
};

export type IuserValidatorOfIdentityUser = {
    [key: string]: never;
};

export type IPasswordValidatorOfIdentityUser = {
    [key: string]: never;
};

export type ILookupNormalizer = {
    [key: string]: never;
};

export type IdentityErrorDescriber = {
    [key: string]: never;
};

export type IdentityOptions = {
    claimsIdentity?: ClaimsIdentityOptions;
    user?: UserOptions;
    password?: PasswordOptions;
    lockout?: LockoutOptions;
    signIn?: SignInOptions;
    tokens?: TokenOptions;
    stores?: StoreOptions;
};

export type ClaimsIdentityOptions = {
    roleClaimType?: string;
    userNameClaimType?: string;
    userIdClaimType?: string;
    emailClaimType?: string;
    securityStampClaimType?: string;
};

export type UserOptions = {
    allowedUserNameCharacters?: string;
    requireUniqueEmail?: boolean;
};

export type PasswordOptions = {
    requiredLength?: number;
    requiredUniqueChars?: number;
    requireNonAlphanumeric?: boolean;
    requireLowercase?: boolean;
    requireUppercase?: boolean;
    requireDigit?: boolean;
};

export type LockoutOptions = {
    allowedForNewUsers?: boolean;
    maxFailedAccessAttempts?: number;
    defaultLockoutTimeSpan?: string;
};

export type SignInOptions = {
    requireConfirmedEmail?: boolean;
    requireConfirmedPhoneNumber?: boolean;
    requireConfirmedAccount?: boolean;
};

export type TokenOptions = {
    providerMap?: {
        [key: string]: TokenProviderDescriptor;
    };
    emailConfirmationTokenProvider?: string;
    passwordResetTokenProvider?: string;
    changeEmailTokenProvider?: string;
    changePhoneNumberTokenProvider?: string;
    authenticatorTokenProvider?: string;
    authenticatorIssuer?: string;
};

export type TokenProviderDescriptor = {
    providerType?: string;
    providerInstance?: unknown;
};

export type StoreOptions = {
    maxLengthForKeys?: number;
    protectPersonalData?: boolean;
    schemaVersion?: string;
};

export type IServiceProvider = {
    [key: string]: never;
};

export type IdentityUser = IdentityUserOfString & {};

export type IdentityUserOfString = {
    id?: string | null;
    userName?: string | null;
    normalizedUserName?: string | null;
    email?: string | null;
    normalizedEmail?: string | null;
    emailConfirmed?: boolean;
    passwordHash?: string | null;
    securityStamp?: string | null;
    concurrencyStamp?: string | null;
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: string | null;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
};

export type IuserClaimsPrincipalFactoryOfIdentityUser = {
    [key: string]: never;
};

export type HttpContext = {
    [key: string]: never;
};

export type AddMembersRequest = {
    memberIds: Array<string>;
};

export type ProblemDetails2 = {
    type?: string;
    title?: string;
    status?: number;
    instance?: string;
    traceId?: string;
    detail?: string | null;
    errors?: Array<ProblemDetailsError>;
};

export type ProblemDetailsError = {
    name?: string;
    reason?: string;
    code?: string | null;
    severity?: string | null;
};

export type CreateDirectMessageRequest = {
    recipientId?: string;
};

export type CreateRoomResponse = {
    roomId?: string;
};

export type CreateRoomRequest = {
    name?: string;
};

export type GetMessagesResponse = {
    messages?: Array<GetMessagesResponseMessageDto>;
    nextCursor?: string | null;
    hasNextPage?: boolean;
};

export type GetMessagesResponseMessageDto = {
    id?: string;
    content?: string;
    senderId?: string;
    timestamp?: string;
};

export type GetMessagesRequest = {
    [key: string]: never;
};

export type ListRoomResponse = {
    rooms?: Array<RoomDto>;
};

export type RoomDto = {
    id: string;
    name: string;
    type: string;
};

export type SendMessagesRequest = {
    content?: string;
};

export type ListUsersResponse = {
    data?: Array<UserResponseDto>;
};

export type UserResponseDto = {
    id?: string;
    username?: string;
    lastSeenAt?: string;
    isOnline?: boolean;
};

export type PostRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    400: HttpValidationProblemDetails;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    200: unknown;
};

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean | null;
        useSessionCookies?: boolean | null;
    };
    url: '/login';
};

export type PostLoginResponses = {
    200: AccessTokenResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    200: AccessTokenResponse;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type GetConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string | null;
        code: string | null;
        changedEmail?: string | null;
    };
    url: '/confirmEmail';
};

export type GetConfirmEmailResponses = {
    200: unknown;
};

export type PostResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/resendConfirmationEmail';
};

export type PostResendConfirmationEmailResponses = {
    200: unknown;
};

export type PostForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/forgotPassword';
};

export type PostForgotPasswordErrors = {
    400: HttpValidationProblemDetails;
};

export type PostForgotPasswordError = PostForgotPasswordErrors[keyof PostForgotPasswordErrors];

export type PostForgotPasswordResponses = {
    200: unknown;
};

export type PostResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/resetPassword';
};

export type PostResetPasswordErrors = {
    400: HttpValidationProblemDetails;
};

export type PostResetPasswordError = PostResetPasswordErrors[keyof PostResetPasswordErrors];

export type PostResetPasswordResponses = {
    200: unknown;
};

export type PostManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/manage/2fa';
};

export type PostManage2FaErrors = {
    400: HttpValidationProblemDetails;
    404: unknown;
};

export type PostManage2FaError = PostManage2FaErrors[keyof PostManage2FaErrors];

export type PostManage2FaResponses = {
    200: TwoFactorResponse;
};

export type PostManage2FaResponse = PostManage2FaResponses[keyof PostManage2FaResponses];

export type GetManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type GetManageInfoErrors = {
    400: HttpValidationProblemDetails;
    404: unknown;
};

export type GetManageInfoError = GetManageInfoErrors[keyof GetManageInfoErrors];

export type GetManageInfoResponses = {
    200: InfoResponse;
};

export type GetManageInfoResponse = GetManageInfoResponses[keyof GetManageInfoResponses];

export type PostManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type PostManageInfoErrors = {
    400: HttpValidationProblemDetails;
    404: unknown;
};

export type PostManageInfoError = PostManageInfoErrors[keyof PostManageInfoErrors];

export type PostManageInfoResponses = {
    200: InfoResponse;
};

export type PostManageInfoResponse = PostManageInfoResponses[keyof PostManageInfoResponses];

export type PostLogoutData = {
    body: SignInManagerOfIdentityUser;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutResponses = {
    200: unknown;
};

export type AddMembersData = {
    body: AddMembersRequest;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/rooms/{roomId}/members';
};

export type AddMembersErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails2;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type AddMembersError = AddMembersErrors[keyof AddMembersErrors];

export type AddMembersResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AddMembersResponse = AddMembersResponses[keyof AddMembersResponses];

export type CreateDirectMessageData = {
    body: CreateDirectMessageRequest;
    path?: never;
    query?: never;
    url: '/rooms/dm';
};

export type CreateDirectMessageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CreateDirectMessageResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CreateDirectMessageResponse = CreateDirectMessageResponses[keyof CreateDirectMessageResponses];

export type ListRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type ListRoomsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListRoomsResponses = {
    /**
     * Success
     */
    200: ListRoomResponse;
};

export type ListRoomsResponse = ListRoomsResponses[keyof ListRoomsResponses];

export type CreateRoomData = {
    body: CreateRoomRequest;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type CreateRoomErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CreateRoomResponses = {
    /**
     * Success
     */
    200: CreateRoomResponse;
};

export type CreateRoomResponse2 = CreateRoomResponses[keyof CreateRoomResponses];

export type GetMessagesData = {
    body?: never;
    path: {
        roomId: string;
    };
    query: {
        cursor?: string | null;
        limit: number;
    };
    url: '/rooms/{roomId}/messages';
};

export type GetMessagesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetMessagesResponses = {
    /**
     * Success
     */
    200: GetMessagesResponse;
};

export type GetMessagesResponse2 = GetMessagesResponses[keyof GetMessagesResponses];

export type SendMessagesData = {
    body: SendMessagesRequest;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/rooms/{roomId}/messages';
};

export type SendMessagesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type SendMessagesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SendMessagesResponse = SendMessagesResponses[keyof SendMessagesResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListUsersResponses = {
    /**
     * Success
     */
    200: ListUsersResponse;
};

export type ListUsersResponse2 = ListUsersResponses[keyof ListUsersResponses];
