// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type MicrosoftAspNetCoreHttpHttpValidationProblemDetails = MicrosoftAspNetCoreMvcProblemDetails & {
    errors?: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown;
};

export type MicrosoftAspNetCoreMvcProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type MicrosoftAspNetCoreIdentityDataRegisterRequest = {
    email: string;
    password: string;
};

export type MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse = {
    tokenType?: string;
    accessToken: string;
    expiresIn: number;
    refreshToken: string;
};

export type MicrosoftAspNetCoreIdentityDataLoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: string | null;
    twoFactorRecoveryCode?: string | null;
};

export type MicrosoftAspNetCoreIdentityDataRefreshRequest = {
    refreshToken: string;
};

export type MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest = {
    email: string;
};

export type MicrosoftAspNetCoreIdentityDataForgotPasswordRequest = {
    email: string;
};

export type MicrosoftAspNetCoreIdentityDataResetPasswordRequest = {
    email: string;
    resetCode: string;
    newPassword: string;
};

export type MicrosoftAspNetCoreIdentityDataTwoFactorResponse = {
    sharedKey: string;
    recoveryCodesLeft: number;
    recoveryCodes?: Array<string> | null;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type MicrosoftAspNetCoreIdentityDataTwoFactorRequest = {
    enable?: boolean | null;
    twoFactorCode?: string | null;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type MicrosoftAspNetCoreIdentityDataInfoResponse = {
    email: string;
    isEmailConfirmed: boolean;
};

export type MicrosoftAspNetCoreIdentityDataInfoRequest = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

export type MicrosoftAspNetCoreIdentitySignInManagerOfIdentityUser = {
    logger?: MicrosoftExtensionsLoggingILogger;
    userManager?: MicrosoftAspNetCoreIdentityUserManagerOfIdentityUser;
    claimsFactory?: MicrosoftAspNetCoreIdentityIuserClaimsPrincipalFactoryOfIdentityUser;
    options?: MicrosoftAspNetCoreIdentityIdentityOptions;
    authenticationScheme?: string;
    context?: MicrosoftAspNetCoreHttpHttpContext;
};

export type MicrosoftExtensionsLoggingILogger = {
    [key: string]: never;
};

export type MicrosoftAspNetCoreIdentityUserManagerOfIdentityUser = {
    logger?: MicrosoftExtensionsLoggingILogger;
    passwordHasher?: MicrosoftAspNetCoreIdentityIPasswordHasherOfIdentityUser;
    userValidators?: Array<MicrosoftAspNetCoreIdentityIuserValidatorOfIdentityUser>;
    passwordValidators?: Array<MicrosoftAspNetCoreIdentityIPasswordValidatorOfIdentityUser>;
    keyNormalizer?: MicrosoftAspNetCoreIdentityILookupNormalizer;
    errorDescriber?: MicrosoftAspNetCoreIdentityIdentityErrorDescriber;
    options?: MicrosoftAspNetCoreIdentityIdentityOptions;
    serviceProvider?: SystemIServiceProvider;
    supportsUserAuthenticationTokens?: boolean;
    supportsUserAuthenticatorKey?: boolean;
    supportsUserTwoFactorRecoveryCodes?: boolean;
    supportsUserTwoFactor?: boolean;
    supportsUserPassword?: boolean;
    supportsUserSecurityStamp?: boolean;
    supportsUserRole?: boolean;
    supportsUserLogin?: boolean;
    supportsUserEmail?: boolean;
    supportsUserPhoneNumber?: boolean;
    supportsUserClaim?: boolean;
    supportsUserLockout?: boolean;
    supportsQueryableUsers?: boolean;
    supportsUserPasskey?: boolean;
    users?: Array<MicrosoftAspNetCoreIdentityIdentityUser>;
};

export type MicrosoftAspNetCoreIdentityIPasswordHasherOfIdentityUser = {
    [key: string]: never;
};

export type MicrosoftAspNetCoreIdentityIuserValidatorOfIdentityUser = {
    [key: string]: never;
};

export type MicrosoftAspNetCoreIdentityIPasswordValidatorOfIdentityUser = {
    [key: string]: never;
};

export type MicrosoftAspNetCoreIdentityILookupNormalizer = {
    [key: string]: never;
};

export type MicrosoftAspNetCoreIdentityIdentityErrorDescriber = {
    [key: string]: never;
};

export type MicrosoftAspNetCoreIdentityIdentityOptions = {
    claimsIdentity?: MicrosoftAspNetCoreIdentityClaimsIdentityOptions;
    user?: MicrosoftAspNetCoreIdentityUserOptions;
    password?: MicrosoftAspNetCoreIdentityPasswordOptions;
    lockout?: MicrosoftAspNetCoreIdentityLockoutOptions;
    signIn?: MicrosoftAspNetCoreIdentitySignInOptions;
    tokens?: MicrosoftAspNetCoreIdentityTokenOptions;
    stores?: MicrosoftAspNetCoreIdentityStoreOptions;
};

export type MicrosoftAspNetCoreIdentityClaimsIdentityOptions = {
    roleClaimType?: string;
    userNameClaimType?: string;
    userIdClaimType?: string;
    emailClaimType?: string;
    securityStampClaimType?: string;
};

export type MicrosoftAspNetCoreIdentityUserOptions = {
    allowedUserNameCharacters?: string;
    requireUniqueEmail?: boolean;
};

export type MicrosoftAspNetCoreIdentityPasswordOptions = {
    requiredLength?: number;
    requiredUniqueChars?: number;
    requireNonAlphanumeric?: boolean;
    requireLowercase?: boolean;
    requireUppercase?: boolean;
    requireDigit?: boolean;
};

export type MicrosoftAspNetCoreIdentityLockoutOptions = {
    allowedForNewUsers?: boolean;
    maxFailedAccessAttempts?: number;
    defaultLockoutTimeSpan?: string;
};

export type MicrosoftAspNetCoreIdentitySignInOptions = {
    requireConfirmedEmail?: boolean;
    requireConfirmedPhoneNumber?: boolean;
    requireConfirmedAccount?: boolean;
};

export type MicrosoftAspNetCoreIdentityTokenOptions = {
    providerMap?: {
        [key: string]: MicrosoftAspNetCoreIdentityTokenProviderDescriptor;
    };
    emailConfirmationTokenProvider?: string;
    passwordResetTokenProvider?: string;
    changeEmailTokenProvider?: string;
    changePhoneNumberTokenProvider?: string;
    authenticatorTokenProvider?: string;
    authenticatorIssuer?: string;
};

export type MicrosoftAspNetCoreIdentityTokenProviderDescriptor = {
    providerType?: string;
    providerInstance?: unknown;
};

export type MicrosoftAspNetCoreIdentityStoreOptions = {
    maxLengthForKeys?: number;
    protectPersonalData?: boolean;
    schemaVersion?: string;
};

export type SystemIServiceProvider = {
    [key: string]: never;
};

export type MicrosoftAspNetCoreIdentityIdentityUser = MicrosoftAspNetCoreIdentityIdentityUserOfString & {};

export type MicrosoftAspNetCoreIdentityIdentityUserOfString = {
    id?: string | null;
    userName?: string | null;
    normalizedUserName?: string | null;
    email?: string | null;
    normalizedEmail?: string | null;
    emailConfirmed?: boolean;
    passwordHash?: string | null;
    securityStamp?: string | null;
    concurrencyStamp?: string | null;
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: string | null;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
};

export type MicrosoftAspNetCoreIdentityIuserClaimsPrincipalFactoryOfIdentityUser = {
    [key: string]: never;
};

export type MicrosoftAspNetCoreHttpHttpContext = {
    [key: string]: never;
};

export type ServerModulesRoomsAddMembersAddMembersRequest = {
    memberIds: Array<string>;
};

export type FastEndpointsProblemDetails = {
    type?: string;
    title?: string;
    status?: number;
    instance?: string;
    traceId?: string;
    detail?: string | null;
    errors?: Array<FastEndpointsProblemDetailsError>;
};

export type FastEndpointsProblemDetailsError = {
    name?: string;
    reason?: string;
    code?: string | null;
    severity?: string | null;
};

export type ServerModulesRoomsCreateDirectMessageCreateDirectMessageRequest = {
    recipientId: string;
};

export type ServerModulesRoomsCreateRoomCreateRoomResponse = {
    roomId: string;
};

export type ServerModulesRoomsCreateRoomCreateRoomRequest = {
    name: string;
};

export type ServerModulesRoomsGetMessagesGetMessagesResponse = {
    messages?: Array<ServerModulesRoomsGetMessagesGetMessagesResponseMessageDto>;
    nextCursor?: string | null;
    hasNextPage?: boolean;
};

export type ServerModulesRoomsGetMessagesGetMessagesResponseMessageDto = {
    id?: string;
    content?: string;
    senderId?: string;
    timestamp?: string;
};

export type ServerModulesRoomsGetMessagesGetMessagesRequest = {
    [key: string]: never;
};

export type ServerModulesRoomsListRoomsListRoomResponse = {
    rooms?: Array<ServerModulesRoomsListRoomsRoomDto>;
};

export type ServerModulesRoomsListRoomsRoomDto = {
    id: string;
    name: string;
    type: string;
};

export type ServerModulesRoomsSendMessagesSendMessagesRequest = {
    content: string;
};

export type ServerModulesUsersListUsersListUsersResponse = {
    data?: Array<ServerModulesUsersListUsersUserResponseDto>;
};

export type ServerModulesUsersListUsersUserResponseDto = {
    id?: string;
    username?: string;
    lastSeenAt?: string;
    isOnline?: boolean;
};

export type PostRegisterData = {
    body: MicrosoftAspNetCoreIdentityDataRegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    200: unknown;
};

export type PostLoginData = {
    body: MicrosoftAspNetCoreIdentityDataLoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean | null;
        useSessionCookies?: boolean | null;
    };
    url: '/login';
};

export type PostLoginResponses = {
    200: MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostRefreshData = {
    body: MicrosoftAspNetCoreIdentityDataRefreshRequest;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    200: MicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type GetConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string | null;
        code: string | null;
        changedEmail?: string | null;
    };
    url: '/confirmEmail';
};

export type GetConfirmEmailResponses = {
    200: unknown;
};

export type PostResendConfirmationEmailData = {
    body: MicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/resendConfirmationEmail';
};

export type PostResendConfirmationEmailResponses = {
    200: unknown;
};

export type PostForgotPasswordData = {
    body: MicrosoftAspNetCoreIdentityDataForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/forgotPassword';
};

export type PostForgotPasswordErrors = {
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
};

export type PostForgotPasswordError = PostForgotPasswordErrors[keyof PostForgotPasswordErrors];

export type PostForgotPasswordResponses = {
    200: unknown;
};

export type PostResetPasswordData = {
    body: MicrosoftAspNetCoreIdentityDataResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/resetPassword';
};

export type PostResetPasswordErrors = {
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
};

export type PostResetPasswordError = PostResetPasswordErrors[keyof PostResetPasswordErrors];

export type PostResetPasswordResponses = {
    200: unknown;
};

export type PostManage2FaData = {
    body: MicrosoftAspNetCoreIdentityDataTwoFactorRequest;
    path?: never;
    query?: never;
    url: '/manage/2fa';
};

export type PostManage2FaErrors = {
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    404: unknown;
};

export type PostManage2FaError = PostManage2FaErrors[keyof PostManage2FaErrors];

export type PostManage2FaResponses = {
    200: MicrosoftAspNetCoreIdentityDataTwoFactorResponse;
};

export type PostManage2FaResponse = PostManage2FaResponses[keyof PostManage2FaResponses];

export type GetManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type GetManageInfoErrors = {
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    404: unknown;
};

export type GetManageInfoError = GetManageInfoErrors[keyof GetManageInfoErrors];

export type GetManageInfoResponses = {
    200: MicrosoftAspNetCoreIdentityDataInfoResponse;
};

export type GetManageInfoResponse = GetManageInfoResponses[keyof GetManageInfoResponses];

export type PostManageInfoData = {
    body: MicrosoftAspNetCoreIdentityDataInfoRequest;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type PostManageInfoErrors = {
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    404: unknown;
};

export type PostManageInfoError = PostManageInfoErrors[keyof PostManageInfoErrors];

export type PostManageInfoResponses = {
    200: MicrosoftAspNetCoreIdentityDataInfoResponse;
};

export type PostManageInfoResponse = PostManageInfoResponses[keyof PostManageInfoResponses];

export type PostLogoutData = {
    body: MicrosoftAspNetCoreIdentitySignInManagerOfIdentityUser;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutResponses = {
    200: unknown;
};

export type AddMembersData = {
    body: ServerModulesRoomsAddMembersAddMembersRequest;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/rooms/{roomId}/members';
};

export type AddMembersErrors = {
    /**
     * Bad Request
     */
    400: FastEndpointsProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type AddMembersError = AddMembersErrors[keyof AddMembersErrors];

export type AddMembersResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AddMembersResponse = AddMembersResponses[keyof AddMembersResponses];

export type CreateDirectMessageData = {
    body: ServerModulesRoomsCreateDirectMessageCreateDirectMessageRequest;
    path?: never;
    query?: never;
    url: '/rooms/dm';
};

export type CreateDirectMessageErrors = {
    /**
     * Bad Request
     */
    400: FastEndpointsProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CreateDirectMessageError = CreateDirectMessageErrors[keyof CreateDirectMessageErrors];

export type CreateDirectMessageResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CreateDirectMessageResponse = CreateDirectMessageResponses[keyof CreateDirectMessageResponses];

export type ListRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type ListRoomsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListRoomsResponses = {
    /**
     * Success
     */
    200: ServerModulesRoomsListRoomsListRoomResponse;
};

export type ListRoomsResponse = ListRoomsResponses[keyof ListRoomsResponses];

export type CreateRoomData = {
    body: ServerModulesRoomsCreateRoomCreateRoomRequest;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type CreateRoomErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CreateRoomResponses = {
    /**
     * Success
     */
    200: ServerModulesRoomsCreateRoomCreateRoomResponse;
};

export type CreateRoomResponse = CreateRoomResponses[keyof CreateRoomResponses];

export type GetMessagesData = {
    body?: never;
    path: {
        roomId: string;
    };
    query: {
        cursor?: string | null;
        limit: number;
    };
    url: '/rooms/{roomId}/messages';
};

export type GetMessagesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetMessagesResponses = {
    /**
     * Success
     */
    200: ServerModulesRoomsGetMessagesGetMessagesResponse;
};

export type GetMessagesResponse = GetMessagesResponses[keyof GetMessagesResponses];

export type SendMessagesData = {
    body: ServerModulesRoomsSendMessagesSendMessagesRequest;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/rooms/{roomId}/messages';
};

export type SendMessagesErrors = {
    /**
     * Bad Request
     */
    400: FastEndpointsProblemDetails;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type SendMessagesError = SendMessagesErrors[keyof SendMessagesErrors];

export type SendMessagesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SendMessagesResponse = SendMessagesResponses[keyof SendMessagesResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListUsersResponses = {
    /**
     * Success
     */
    200: ServerModulesUsersListUsersListUsersResponse;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];
