// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zMicrosoftAspNetCoreMvcProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish()
});

export const zMicrosoftAspNetCoreHttpHttpValidationProblemDetails = zMicrosoftAspNetCoreMvcProblemDetails.and(z.object({
    errors: z.record(z.string(), z.array(z.string())).optional()
}));

export const zMicrosoftAspNetCoreIdentityDataRegisterRequest = z.object({
    email: z.string(),
    password: z.string()
});

export const zMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse = z.object({
    tokenType: z.string().optional(),
    accessToken: z.string(),
    expiresIn: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    refreshToken: z.string()
});

export const zMicrosoftAspNetCoreIdentityDataLoginRequest = z.object({
    email: z.string(),
    password: z.string(),
    twoFactorCode: z.string().nullish(),
    twoFactorRecoveryCode: z.string().nullish()
});

export const zMicrosoftAspNetCoreIdentityDataRefreshRequest = z.object({
    refreshToken: z.string()
});

export const zMicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest = z.object({
    email: z.string()
});

export const zMicrosoftAspNetCoreIdentityDataForgotPasswordRequest = z.object({
    email: z.string()
});

export const zMicrosoftAspNetCoreIdentityDataResetPasswordRequest = z.object({
    email: z.string(),
    resetCode: z.string(),
    newPassword: z.string()
});

export const zMicrosoftAspNetCoreIdentityDataTwoFactorResponse = z.object({
    sharedKey: z.string(),
    recoveryCodesLeft: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    recoveryCodes: z.array(z.string()).nullish(),
    isTwoFactorEnabled: z.boolean(),
    isMachineRemembered: z.boolean()
});

export const zMicrosoftAspNetCoreIdentityDataTwoFactorRequest = z.object({
    enable: z.boolean().nullish(),
    twoFactorCode: z.string().nullish(),
    resetSharedKey: z.boolean().optional(),
    resetRecoveryCodes: z.boolean().optional(),
    forgetMachine: z.boolean().optional()
});

export const zMicrosoftAspNetCoreIdentityDataInfoResponse = z.object({
    email: z.string(),
    isEmailConfirmed: z.boolean()
});

export const zMicrosoftAspNetCoreIdentityDataInfoRequest = z.object({
    newEmail: z.string().nullish(),
    newPassword: z.string().nullish(),
    oldPassword: z.string().nullish()
});

export const zMicrosoftExtensionsLoggingILogger = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreIdentityIPasswordHasherOfIdentityUser = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreIdentityIuserValidatorOfIdentityUser = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreIdentityIPasswordValidatorOfIdentityUser = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreIdentityILookupNormalizer = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreIdentityIdentityErrorDescriber = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreIdentityClaimsIdentityOptions = z.object({
    roleClaimType: z.string().optional(),
    userNameClaimType: z.string().optional(),
    userIdClaimType: z.string().optional(),
    emailClaimType: z.string().optional(),
    securityStampClaimType: z.string().optional()
});

export const zMicrosoftAspNetCoreIdentityUserOptions = z.object({
    allowedUserNameCharacters: z.string().optional(),
    requireUniqueEmail: z.boolean().optional()
});

export const zMicrosoftAspNetCoreIdentityPasswordOptions = z.object({
    requiredLength: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    requiredUniqueChars: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    requireNonAlphanumeric: z.boolean().optional(),
    requireLowercase: z.boolean().optional(),
    requireUppercase: z.boolean().optional(),
    requireDigit: z.boolean().optional()
});

export const zMicrosoftAspNetCoreIdentityLockoutOptions = z.object({
    allowedForNewUsers: z.boolean().optional(),
    maxFailedAccessAttempts: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    defaultLockoutTimeSpan: z.string().optional()
});

export const zMicrosoftAspNetCoreIdentitySignInOptions = z.object({
    requireConfirmedEmail: z.boolean().optional(),
    requireConfirmedPhoneNumber: z.boolean().optional(),
    requireConfirmedAccount: z.boolean().optional()
});

export const zMicrosoftAspNetCoreIdentityTokenProviderDescriptor = z.object({
    providerType: z.string().optional(),
    providerInstance: z.unknown().optional()
});

export const zMicrosoftAspNetCoreIdentityTokenOptions = z.object({
    providerMap: z.record(z.string(), zMicrosoftAspNetCoreIdentityTokenProviderDescriptor).optional(),
    emailConfirmationTokenProvider: z.string().optional(),
    passwordResetTokenProvider: z.string().optional(),
    changeEmailTokenProvider: z.string().optional(),
    changePhoneNumberTokenProvider: z.string().optional(),
    authenticatorTokenProvider: z.string().optional(),
    authenticatorIssuer: z.string().optional()
});

export const zMicrosoftAspNetCoreIdentityStoreOptions = z.object({
    maxLengthForKeys: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    protectPersonalData: z.boolean().optional(),
    schemaVersion: z.string().optional()
});

export const zMicrosoftAspNetCoreIdentityIdentityOptions = z.object({
    claimsIdentity: zMicrosoftAspNetCoreIdentityClaimsIdentityOptions.optional(),
    user: zMicrosoftAspNetCoreIdentityUserOptions.optional(),
    password: zMicrosoftAspNetCoreIdentityPasswordOptions.optional(),
    lockout: zMicrosoftAspNetCoreIdentityLockoutOptions.optional(),
    signIn: zMicrosoftAspNetCoreIdentitySignInOptions.optional(),
    tokens: zMicrosoftAspNetCoreIdentityTokenOptions.optional(),
    stores: zMicrosoftAspNetCoreIdentityStoreOptions.optional()
});

export const zSystemIServiceProvider = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreIdentityIdentityUserOfString = z.object({
    id: z.string().nullish(),
    userName: z.string().nullish(),
    normalizedUserName: z.string().nullish(),
    email: z.string().nullish(),
    normalizedEmail: z.string().nullish(),
    emailConfirmed: z.boolean().optional(),
    passwordHash: z.string().nullish(),
    securityStamp: z.string().nullish(),
    concurrencyStamp: z.string().nullish(),
    phoneNumber: z.string().nullish(),
    phoneNumberConfirmed: z.boolean().optional(),
    twoFactorEnabled: z.boolean().optional(),
    lockoutEnd: z.iso.datetime().nullish(),
    lockoutEnabled: z.boolean().optional(),
    accessFailedCount: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zMicrosoftAspNetCoreIdentityIdentityUser = zMicrosoftAspNetCoreIdentityIdentityUserOfString.and(z.object({}));

export const zMicrosoftAspNetCoreIdentityUserManagerOfIdentityUser = z.object({
    logger: zMicrosoftExtensionsLoggingILogger.optional(),
    passwordHasher: zMicrosoftAspNetCoreIdentityIPasswordHasherOfIdentityUser.optional(),
    userValidators: z.array(zMicrosoftAspNetCoreIdentityIuserValidatorOfIdentityUser).optional(),
    passwordValidators: z.array(zMicrosoftAspNetCoreIdentityIPasswordValidatorOfIdentityUser).optional(),
    keyNormalizer: zMicrosoftAspNetCoreIdentityILookupNormalizer.optional(),
    errorDescriber: zMicrosoftAspNetCoreIdentityIdentityErrorDescriber.optional(),
    options: zMicrosoftAspNetCoreIdentityIdentityOptions.optional(),
    serviceProvider: zSystemIServiceProvider.optional(),
    supportsUserAuthenticationTokens: z.boolean().optional(),
    supportsUserAuthenticatorKey: z.boolean().optional(),
    supportsUserTwoFactorRecoveryCodes: z.boolean().optional(),
    supportsUserTwoFactor: z.boolean().optional(),
    supportsUserPassword: z.boolean().optional(),
    supportsUserSecurityStamp: z.boolean().optional(),
    supportsUserRole: z.boolean().optional(),
    supportsUserLogin: z.boolean().optional(),
    supportsUserEmail: z.boolean().optional(),
    supportsUserPhoneNumber: z.boolean().optional(),
    supportsUserClaim: z.boolean().optional(),
    supportsUserLockout: z.boolean().optional(),
    supportsQueryableUsers: z.boolean().optional(),
    supportsUserPasskey: z.boolean().optional(),
    users: z.array(zMicrosoftAspNetCoreIdentityIdentityUser).optional()
});

export const zMicrosoftAspNetCoreIdentityIuserClaimsPrincipalFactoryOfIdentityUser = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreHttpHttpContext = z.record(z.string(), z.never());

export const zMicrosoftAspNetCoreIdentitySignInManagerOfIdentityUser = z.object({
    logger: zMicrosoftExtensionsLoggingILogger.optional(),
    userManager: zMicrosoftAspNetCoreIdentityUserManagerOfIdentityUser.optional(),
    claimsFactory: zMicrosoftAspNetCoreIdentityIuserClaimsPrincipalFactoryOfIdentityUser.optional(),
    options: zMicrosoftAspNetCoreIdentityIdentityOptions.optional(),
    authenticationScheme: z.string().optional(),
    context: zMicrosoftAspNetCoreHttpHttpContext.optional()
});

export const zServerModulesRoomsAddMembersAddMembersRequest = z.object({
    memberIds: z.array(z.string())
});

export const zFastEndpointsProblemDetailsError = z.object({
    name: z.string().optional().default('Error or field name'),
    reason: z.string().optional().default('Error reason'),
    code: z.string().nullish(),
    severity: z.string().nullish()
});

export const zFastEndpointsProblemDetails = z.object({
    type: z.string().optional().default('https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1'),
    title: z.string().optional().default('One or more validation errors occurred.'),
    status: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(400),
    instance: z.string().optional().default('/api/route'),
    traceId: z.string().optional().default('0HMPNHL0JHL76:00000001'),
    detail: z.string().nullish(),
    errors: z.array(zFastEndpointsProblemDetailsError).optional()
});

export const zServerModulesRoomsCreateDirectMessageCreateDirectMessageRequest = z.object({
    recipientId: z.string().min(1)
});

export const zServerModulesRoomsCreateRoomCreateRoomResponse = z.object({
    roomId: z.string()
});

export const zServerModulesRoomsCreateRoomCreateRoomRequest = z.object({
    name: z.string()
});

export const zServerModulesRoomsGetMessagesGetMessagesResponseMessageDto = z.object({
    id: z.string().optional(),
    content: z.string().optional(),
    senderId: z.string().optional(),
    timestamp: z.iso.datetime().optional()
});

export const zServerModulesRoomsGetMessagesGetMessagesResponse = z.object({
    messages: z.array(zServerModulesRoomsGetMessagesGetMessagesResponseMessageDto).optional(),
    nextCursor: z.string().nullish(),
    hasNextPage: z.boolean().optional()
});

export const zServerModulesRoomsGetMessagesGetMessagesRequest = z.record(z.string(), z.never());

export const zServerModulesRoomsListRoomsRoomDto = z.object({
    id: z.string(),
    name: z.string(),
    type: z.string()
});

export const zServerModulesRoomsListRoomsListRoomResponse = z.object({
    rooms: z.array(zServerModulesRoomsListRoomsRoomDto).optional()
});

export const zServerModulesRoomsSendMessagesSendMessagesRequest = z.object({
    content: z.string().min(1)
});

export const zServerModulesUsersListUsersUserResponseDto = z.object({
    id: z.string().optional(),
    username: z.string().optional(),
    lastSeenAt: z.iso.datetime().optional(),
    isOnline: z.boolean().optional()
});

export const zServerModulesUsersListUsersListUsersResponse = z.object({
    data: z.array(zServerModulesUsersListUsersUserResponseDto).optional()
});

export const zPostRegisterBody = zMicrosoftAspNetCoreIdentityDataRegisterRequest;

export const zPostLoginBody = zMicrosoftAspNetCoreIdentityDataLoginRequest;

export const zPostLoginQuery = z.object({
    useCookies: z.boolean().nullish(),
    useSessionCookies: z.boolean().nullish()
});

export const zPostLoginResponse = zMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse;

export const zPostRefreshBody = zMicrosoftAspNetCoreIdentityDataRefreshRequest;

export const zPostRefreshResponse = zMicrosoftAspNetCoreAuthenticationBearerTokenAccessTokenResponse;

export const zGetConfirmEmailQuery = z.object({
    userId: z.string().nullable(),
    code: z.string().nullable(),
    changedEmail: z.string().nullish()
});

export const zPostResendConfirmationEmailBody = zMicrosoftAspNetCoreIdentityDataResendConfirmationEmailRequest;

export const zPostForgotPasswordBody = zMicrosoftAspNetCoreIdentityDataForgotPasswordRequest;

export const zPostResetPasswordBody = zMicrosoftAspNetCoreIdentityDataResetPasswordRequest;

export const zPostManage2FaBody = zMicrosoftAspNetCoreIdentityDataTwoFactorRequest;

export const zPostManage2FaResponse = zMicrosoftAspNetCoreIdentityDataTwoFactorResponse;

export const zGetManageInfoResponse = zMicrosoftAspNetCoreIdentityDataInfoResponse;

export const zPostManageInfoBody = zMicrosoftAspNetCoreIdentityDataInfoRequest;

export const zPostManageInfoResponse = zMicrosoftAspNetCoreIdentityDataInfoResponse;

export const zPostLogoutBody = zMicrosoftAspNetCoreIdentitySignInManagerOfIdentityUser;

export const zAddMembersBody = zServerModulesRoomsAddMembersAddMembersRequest;

export const zAddMembersPath = z.object({
    roomId: z.string()
});

/**
 * No Content
 */
export const zAddMembersResponse = z.void();

export const zCreateDirectMessageBody = zServerModulesRoomsCreateDirectMessageCreateDirectMessageRequest;

/**
 * No Content
 */
export const zCreateDirectMessageResponse = z.void();

/**
 * Success
 */
export const zListRoomsResponse = zServerModulesRoomsListRoomsListRoomResponse;

export const zCreateRoomBody = zServerModulesRoomsCreateRoomCreateRoomRequest;

/**
 * Success
 */
export const zCreateRoomResponse = zServerModulesRoomsCreateRoomCreateRoomResponse;

export const zGetMessagesPath = z.object({
    roomId: z.guid()
});

export const zGetMessagesQuery = z.object({
    cursor: z.string().nullish(),
    limit: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).default(50)
});

/**
 * Success
 */
export const zGetMessagesResponse = zServerModulesRoomsGetMessagesGetMessagesResponse;

export const zSendMessagesBody = zServerModulesRoomsSendMessagesSendMessagesRequest;

export const zSendMessagesPath = z.object({
    roomId: z.guid()
});

/**
 * No Content
 */
export const zSendMessagesResponse = z.void();

/**
 * Success
 */
export const zListUsersResponse = zServerModulesUsersListUsersListUsersResponse;
