// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish()
});

export const zHttpValidationProblemDetails = zProblemDetails.and(z.object({
    errors: z.record(z.string(), z.array(z.string())).optional()
}));

export const zRegisterRequest = z.object({
    email: z.string(),
    password: z.string()
});

export const zAccessTokenResponse = z.object({
    tokenType: z.string().optional(),
    accessToken: z.string(),
    expiresIn: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    refreshToken: z.string()
});

export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string(),
    twoFactorCode: z.string().nullish(),
    twoFactorRecoveryCode: z.string().nullish()
});

export const zRefreshRequest = z.object({
    refreshToken: z.string()
});

export const zResendConfirmationEmailRequest = z.object({
    email: z.string()
});

export const zForgotPasswordRequest = z.object({
    email: z.string()
});

export const zResetPasswordRequest = z.object({
    email: z.string(),
    resetCode: z.string(),
    newPassword: z.string()
});

export const zTwoFactorResponse = z.object({
    sharedKey: z.string(),
    recoveryCodesLeft: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    recoveryCodes: z.array(z.string()).nullish(),
    isTwoFactorEnabled: z.boolean(),
    isMachineRemembered: z.boolean()
});

export const zTwoFactorRequest = z.object({
    enable: z.boolean().nullish(),
    twoFactorCode: z.string().nullish(),
    resetSharedKey: z.boolean().optional(),
    resetRecoveryCodes: z.boolean().optional(),
    forgetMachine: z.boolean().optional()
});

export const zInfoResponse = z.object({
    email: z.string(),
    isEmailConfirmed: z.boolean()
});

export const zInfoRequest = z.object({
    newEmail: z.string().nullish(),
    newPassword: z.string().nullish(),
    oldPassword: z.string().nullish()
});

export const zILogger = z.record(z.string(), z.never());

export const zIPasswordHasherOfIdentityUser = z.record(z.string(), z.never());

export const zIuserValidatorOfIdentityUser = z.record(z.string(), z.never());

export const zIPasswordValidatorOfIdentityUser = z.record(z.string(), z.never());

export const zILookupNormalizer = z.record(z.string(), z.never());

export const zIdentityErrorDescriber = z.record(z.string(), z.never());

export const zClaimsIdentityOptions = z.object({
    roleClaimType: z.string().optional(),
    userNameClaimType: z.string().optional(),
    userIdClaimType: z.string().optional(),
    emailClaimType: z.string().optional(),
    securityStampClaimType: z.string().optional()
});

export const zUserOptions = z.object({
    allowedUserNameCharacters: z.string().optional(),
    requireUniqueEmail: z.boolean().optional()
});

export const zPasswordOptions = z.object({
    requiredLength: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    requiredUniqueChars: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    requireNonAlphanumeric: z.boolean().optional(),
    requireLowercase: z.boolean().optional(),
    requireUppercase: z.boolean().optional(),
    requireDigit: z.boolean().optional()
});

export const zLockoutOptions = z.object({
    allowedForNewUsers: z.boolean().optional(),
    maxFailedAccessAttempts: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    defaultLockoutTimeSpan: z.string().optional()
});

export const zSignInOptions = z.object({
    requireConfirmedEmail: z.boolean().optional(),
    requireConfirmedPhoneNumber: z.boolean().optional(),
    requireConfirmedAccount: z.boolean().optional()
});

export const zTokenProviderDescriptor = z.object({
    providerType: z.string().optional(),
    providerInstance: z.unknown().optional()
});

export const zTokenOptions = z.object({
    providerMap: z.record(z.string(), zTokenProviderDescriptor).optional(),
    emailConfirmationTokenProvider: z.string().optional(),
    passwordResetTokenProvider: z.string().optional(),
    changeEmailTokenProvider: z.string().optional(),
    changePhoneNumberTokenProvider: z.string().optional(),
    authenticatorTokenProvider: z.string().optional(),
    authenticatorIssuer: z.string().optional()
});

export const zStoreOptions = z.object({
    maxLengthForKeys: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    protectPersonalData: z.boolean().optional(),
    schemaVersion: z.string().optional()
});

export const zIdentityOptions = z.object({
    claimsIdentity: zClaimsIdentityOptions.optional(),
    user: zUserOptions.optional(),
    password: zPasswordOptions.optional(),
    lockout: zLockoutOptions.optional(),
    signIn: zSignInOptions.optional(),
    tokens: zTokenOptions.optional(),
    stores: zStoreOptions.optional()
});

export const zIServiceProvider = z.record(z.string(), z.never());

export const zIdentityUserOfString = z.object({
    id: z.string().nullish(),
    userName: z.string().nullish(),
    normalizedUserName: z.string().nullish(),
    email: z.string().nullish(),
    normalizedEmail: z.string().nullish(),
    emailConfirmed: z.boolean().optional(),
    passwordHash: z.string().nullish(),
    securityStamp: z.string().nullish(),
    concurrencyStamp: z.string().nullish(),
    phoneNumber: z.string().nullish(),
    phoneNumberConfirmed: z.boolean().optional(),
    twoFactorEnabled: z.boolean().optional(),
    lockoutEnd: z.iso.datetime({ offset: true }).nullish(),
    lockoutEnabled: z.boolean().optional(),
    accessFailedCount: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zIdentityUser = zIdentityUserOfString.and(z.object({}));

export const zUserManagerOfIdentityUser = z.object({
    logger: zILogger.optional(),
    passwordHasher: zIPasswordHasherOfIdentityUser.optional(),
    userValidators: z.array(zIuserValidatorOfIdentityUser).optional(),
    passwordValidators: z.array(zIPasswordValidatorOfIdentityUser).optional(),
    keyNormalizer: zILookupNormalizer.optional(),
    errorDescriber: zIdentityErrorDescriber.optional(),
    options: zIdentityOptions.optional(),
    serviceProvider: zIServiceProvider.optional(),
    supportsUserAuthenticationTokens: z.boolean().optional(),
    supportsUserAuthenticatorKey: z.boolean().optional(),
    supportsUserTwoFactorRecoveryCodes: z.boolean().optional(),
    supportsUserTwoFactor: z.boolean().optional(),
    supportsUserPassword: z.boolean().optional(),
    supportsUserSecurityStamp: z.boolean().optional(),
    supportsUserRole: z.boolean().optional(),
    supportsUserLogin: z.boolean().optional(),
    supportsUserEmail: z.boolean().optional(),
    supportsUserPhoneNumber: z.boolean().optional(),
    supportsUserClaim: z.boolean().optional(),
    supportsUserLockout: z.boolean().optional(),
    supportsQueryableUsers: z.boolean().optional(),
    supportsUserPasskey: z.boolean().optional(),
    users: z.array(zIdentityUser).optional()
});

export const zIuserClaimsPrincipalFactoryOfIdentityUser = z.record(z.string(), z.never());

export const zHttpContext = z.record(z.string(), z.never());

export const zSignInManagerOfIdentityUser = z.object({
    logger: zILogger.optional(),
    userManager: zUserManagerOfIdentityUser.optional(),
    claimsFactory: zIuserClaimsPrincipalFactoryOfIdentityUser.optional(),
    options: zIdentityOptions.optional(),
    authenticationScheme: z.string().optional(),
    context: zHttpContext.optional()
});

export const zAddMembersRequest = z.object({
    memberIds: z.array(z.string())
});

export const zProblemDetailsError = z.object({
    name: z.string().optional().default('Error or field name'),
    reason: z.string().optional().default('Error reason'),
    code: z.string().nullish(),
    severity: z.string().nullish()
});

export const zProblemDetails2 = z.object({
    type: z.string().optional().default('https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1'),
    title: z.string().optional().default('One or more validation errors occurred.'),
    status: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(400),
    instance: z.string().optional().default('/api/route'),
    traceId: z.string().optional().default('0HMPNHL0JHL76:00000001'),
    detail: z.string().nullish(),
    errors: z.array(zProblemDetailsError).optional()
});

export const zCreateDirectMessageRequest = z.object({
    recipientId: z.string().optional()
});

export const zCreateRoomResponse = z.object({
    roomId: z.string().optional()
});

export const zCreateRoomRequest = z.object({
    name: z.string().optional()
});

export const zGetMessagesResponseMessageDto = z.object({
    id: z.string().optional(),
    content: z.string().optional(),
    senderId: z.string().optional(),
    timestamp: z.iso.datetime({ offset: true }).optional()
});

export const zGetMessagesResponse = z.object({
    messages: z.array(zGetMessagesResponseMessageDto).optional(),
    nextCursor: z.string().nullish(),
    hasNextPage: z.boolean().optional()
});

export const zGetMessagesRequest = z.record(z.string(), z.never());

export const zRoomDto = z.object({
    id: z.string(),
    name: z.string(),
    type: z.string()
});

export const zListRoomResponse = z.object({
    rooms: z.array(zRoomDto).optional()
});

export const zSendMessagesRequest = z.object({
    content: z.string().optional()
});

export const zUserResponseDto = z.object({
    id: z.string().optional(),
    username: z.string().optional(),
    lastSeenAt: z.iso.datetime({ offset: true }).optional(),
    isOnline: z.boolean().optional()
});

export const zListUsersResponse = z.object({
    data: z.array(zUserResponseDto).optional()
});

export const zPostRegisterBody = zRegisterRequest;

export const zPostLoginBody = zLoginRequest;

export const zPostLoginQuery = z.object({
    useCookies: z.boolean().nullish(),
    useSessionCookies: z.boolean().nullish()
});

export const zPostLoginResponse = zAccessTokenResponse;

export const zPostRefreshBody = zRefreshRequest;

export const zPostRefreshResponse = zAccessTokenResponse;

export const zGetConfirmEmailQuery = z.object({
    userId: z.string().nullable(),
    code: z.string().nullable(),
    changedEmail: z.string().nullish()
});

export const zPostResendConfirmationEmailBody = zResendConfirmationEmailRequest;

export const zPostForgotPasswordBody = zForgotPasswordRequest;

export const zPostResetPasswordBody = zResetPasswordRequest;

export const zPostManage2FaBody = zTwoFactorRequest;

export const zPostManage2FaResponse = zTwoFactorResponse;

export const zGetManageInfoResponse = zInfoResponse;

export const zPostManageInfoBody = zInfoRequest;

export const zPostManageInfoResponse = zInfoResponse;

export const zPostLogoutBody = zSignInManagerOfIdentityUser;

export const zAddMembersBody = zAddMembersRequest;

export const zAddMembersPath = z.object({
    roomId: z.string()
});

/**
 * No Content
 */
export const zAddMembersResponse = z.void();

export const zCreateDirectMessageBody = zCreateDirectMessageRequest;

/**
 * No Content
 */
export const zCreateDirectMessageResponse = z.void();

/**
 * Success
 */
export const zListRoomsResponse = zListRoomResponse;

export const zCreateRoomBody = zCreateRoomRequest;

/**
 * Success
 */
export const zCreateRoomResponse2 = zCreateRoomResponse;

export const zGetMessagesPath = z.object({
    roomId: z.guid()
});

export const zGetMessagesQuery = z.object({
    cursor: z.string().nullish(),
    limit: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).default(50)
});

/**
 * Success
 */
export const zGetMessagesResponse2 = zGetMessagesResponse;

export const zSendMessagesBody = zSendMessagesRequest;

export const zSendMessagesPath = z.object({
    roomId: z.guid()
});

/**
 * No Content
 */
export const zSendMessagesResponse = z.void();

/**
 * Success
 */
export const zListUsersResponse2 = zListUsersResponse;
